AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "Gemfile.lock"
    - "Gemfile"
    - "app"
    - "config"
  DisplayCopNames: true

Metrics/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20
Metrics/AbcSize:
  Include: ["app/controllers/*"]
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
# Style/HashEachMethods:
#   Enabled: true
# Style/HashTransformKeys:
#   Enabled: true
# Style/HashTransformValues:
#   Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Max: 120
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented